### ISSUE TITLE
Application stops responding after approx 48 hours

### ISSUE THREAD

**Issue by roddenshaw** [hoobs-org/soma-connect#1]
I installed a fresh copy of Hoobs on my raspberry pi, and then installed Soma Connect. I am finding that approximately every 48 hours the two Soma devices stop responding in HomeKit, though the devices controlled via Hoobs continue to respond. 

I've tried to look at the logs for the app and it seems to be constantly scanning for devices, which I imagine could be the problem. It's impossible to reproduce the logs because there are four or five lines per second.

Having run systemctl status soma-connect I get the following returned: 

● soma-connect.service - Soma-Connect Server
   Loaded: loaded (/etc/systemd/system/soma-connect.service; enabled; vendor pre
   Active: active (running) since Sun 2020-03-22 13:42:59 MDT; 1min 2s ago
 Main PID: 584 (soma-connect)
    Tasks: 9 (limit: 2200)
   Memory: 72.4M
   CGroup: /system.slice/soma-connect.service
           └─584 /usr/lib/soma-connect/soma-connect

Mar 22 13:43:52 hoobs soma-connect[584]: [[13:43:52.685]] [LOG]   scanning - alr
Mar 22 13:43:52 hoobs soma-connect[584]: [[13:43:52.716]] [LOG]   scanning - alr
Mar 22 13:43:52 hoobs soma-connect[584]: [[13:43:52.731]] [LOG]   SomaApp: mac: 
Mar 22 13:43:52 hoobs soma-connect[584]: [[13:43:52.732]] [LOG]   SomaApp: mac: 
Mar 22 13:44:02 hoobs soma-connect[584]: [[13:44:02.401]] [LOG]   scanning - alr
Mar 22 13:44:02 hoobs soma-connect[584]: [[13:44:02.427]] [LOG]   scanning - alr
Mar 22 13:44:02 hoobs soma-connect[584]: [[13:44:02.501]] [LOG]   scanning - alr
Mar 22 13:44:02 hoobs soma-connect[584]: [[13:44:02.507]] [LOG]   scanning - alr
Mar 22 13:44:02 hoobs soma-connect[584]: [[13:44:02.605]] [LOG]   scanning - alr
Mar 22 13:44:02 hoobs soma-connect[584]: [[13:44:02.648]] [LOG]   scanning - alr
lines 1-19/19 (END)

Does that look correct?

**Comment by roddenshaw** [comment]
This time it stopped responding after 90 minutes. In the Apple Home app both of my blinds say 'no response'. This is what I get when I check the service status:

 soma-connect.service - Soma-Connect Server
   Loaded: loaded (/etc/systemd/system/soma-connect.service; enabled; vendor pre
   Active: active (running) since Sun 2020-03-22 13:42:59 MDT; 1h 33min ago
 Main PID: 584 (soma-connect)
    Tasks: 9 (limit: 2200)
   Memory: 82.7M
   CGroup: /system.slice/soma-connect.service
           └─584 /usr/lib/soma-connect/soma-connect

Mar 22 15:16:34 hoobs soma-connect[584]: [[15:16:34.797]] [LOG]   scanning - alr
Mar 22 15:16:34 hoobs soma-connect[584]: [[15:16:34.888]] [LOG]   scanning - alr
Mar 22 15:16:34 hoobs soma-connect[584]: [[15:16:34.963]] [LOG]   SomaApp: mac: 
Mar 22 15:16:34 hoobs soma-connect[584]: [[15:16:34.963]] [LOG]   SomaApp: mac: 
Mar 22 15:16:35 hoobs soma-connect[584]: [[15:16:35.048]] [LOG]   scanning - alr
Mar 22 15:16:35 hoobs soma-connect[584]: [[15:16:35.068]] [LOG]   SomaApp: mac: 
Mar 22 15:16:35 hoobs soma-connect[584]: [[15:16:35.069]] [LOG]   SomaApp: mac: 
Mar 22 15:16:35 hoobs soma-connect[584]: [[15:16:35.070]] [LOG]   SomaApp: mac: 
Mar 22 15:16:35 hoobs soma-connect[584]: [[15:16:35.070]] [LOG]   running count 
Mar 22 15:16:35 hoobs soma-connect[584]: [[15:16:35.108]] [LOG]   scanning - alr
lines 1-19/19 (END)

**Comment by vhardono** [comment]
@roddenshaw how did you the issue?
I have exactly same issue here. Tried to reformat/reinstall HOOBS, Soma Connect, but after few hours the blind status in Homekit will turn to “No Response”
