### ISSUE TITLE
After Installation Wifi Issue on PI 4

### ISSUE THREAD

**Issue by toellbe** [hoobs-org/soma-connect#2]
After installation and reboot PI 4 is not accessible over Wifi anymore if eth0 not plugged..

**Comment by toellbe** [comment]
I think ifplugd is the cause. Does somebody has any idea? 
Hoobs 3.2.4

**Comment by costispavlou** [comment]
was wondering if you managed to resolve the issue. 
after installing this and rebooting, the pi is on a restart loop

**Comment by mkellsy** [comment]
Stale
