### ISSUE TITLE
Current Version of Soma is 2.0.12

### ISSUE THREAD

**Issue by toellbe** [hoobs-org/soma-connect#4]
Will this be still updated?

**Comment by lbouriez** [comment]
I found it in the current image (version 2.0.12)
[soma-connect_2.0.8_armhf.deb.gz](https://github.com/hoobs-org/soma-connect/files/4647785/soma-connect_2.0.8_armhf.deb.gz)

**Comment by toellbe** [comment]
I will give a try...

**Comment by toellbe** [comment]
Seems to work. 
I just had to create a fake file so that the installation script would not run into an error.

**Comment by lbouriez** [comment]
I am trying to install it inside a docker container but without success...
What are all the steps that you are doing and from Wich base ?

**Comment by toellbe** [comment]
Just as it is described here on github.  I just had to create an empty file: sudo nano /etc/dhcp/dhclient-enter-hooks.d/samba.

 Afterwards the installation was successful sudo dpkg -i —force-all soma-connect

**Comment by roddenshaw** [comment]
Thanks for uploading the 2.0.8 file. I decompressed it and installed it following the same steps as 1.8.7, which worked fine. Happily it seems to have solved the fundamental problem I was having with the previous version, and it has made the blind accessories much more responsive in Home. I’m hoping 2.0.12 will become available at some point, but for now it’s nice to have a stable version running.

**Comment by lbouriez** [comment]
I am not sure how works the creation of a dpkg but I think you can download the last 2.0.12 and extract what you need :)

**Comment by mmmrvn** [comment]
> I found it in the current image (version 2.0.12)
> [soma-connect_2.0.8_armhf.deb.gz](https://github.com/hoobs-org/soma-connect/files/4647785/soma-connect_2.0.8_armhf.deb.gz)

Hi, also requesting if you could upload the .deb of 2.0.12 as I'm unfamiliar with how to extract and create a dpkg. This'll be much appreciated.

**Comment by bubez81** [comment]
hello please can someone give the link to the new version?

**Comment by roddenshaw** [comment]
Somebody posted instructions for how to extract the .deb on the Home Assistant forum. I’m running an iPad Pro as my main computer just now so I can’t do it, but maybe somebody else can take a crack at it: https://community.home-assistant.io/t/soma-smart-shades-2/202224

Also I spoke to somebody at Soma about this a few months ago and he said he would provide the .deb to the person who created this, but I don’t know if that ever happened.

**Comment by bubez81** [comment]
ok today I'll extract the deb and post it here

**Comment by mmmrvn** [comment]
> ok today I'll extract the deb and post it here

Oh wow thanks @bubez81 and @roddenshaw, been waiting for progress regarding this. Could you also post the step by step instructions on how to update this plugin with it already installed on version 1.8.37? Basically a noob, would definitely be grateful

**Comment by bubez81** [comment]
here is the deb file https://www.dropbox.com/s/3ock4c79yzee1np/soma-connect_2.1.1_armhf.deb?dl=0

**Comment by roddenshaw** [comment]
My system seems to think this is actually. 2.0.8, which I already have installed. Odd.

**Comment by roddenshaw** [comment]
Worked it out. The command I needed was sudo dpkg --install soma-connect_2.1.1_armhf.deb?dl=0. I’m having other problems but hopefully I’ll work those out.

**Comment by roddenshaw** [comment]
I had to install Samba to get the soma-connect service up and running, but I can’t add it to HomeKit (it doesn’t appear and the code does nothing). Is anybody else having problems?

**Comment by mmmrvn** [comment]
> sudo dpkg --install soma-connect.deb

But how do you point it to the .deb? When I command "sudo dpkg --install soma-connect_2.1.1_armhf.deb?dl=0" it tells me that there's no such file or directory

**Comment by mmmrvn** [comment]
"sudo wget https://github.com/hoobs-org/soma-connect/releases/download/2.1.1/soma-connect_2.1.1_armhf.deb -O soma-connect.deb" doesn't work either. Results in Error 404 Not Found.

**Comment by bubez81** [comment]
sorry this is the package I provided https://www.dropbox.com/s/3ock4c79yzee1np/soma-connect_2.1.1_armhf.deb?dl=0

you have to download it and than sudo dpkg --install soma-connect_2.1.1_armhf.deb

**Comment by bubez81** [comment]
sadly I can't try the app because I need to change the port 3000 and for now the application does not allow it

**Comment by mkellsy** [comment]
2.2.0 is published

See issue
https://github.com/hoobs-org/soma-connect/issues/7#issuecomment-822972110
