### ISSUE TITLE
help

### ISSUE THREAD

**Issue by andyw77** [hoobs-org/soma-connect#6]
hi, am really new to this. how do I update soma blinds. i have down loaded the file from the conversation but not sure how to put it on my Raspi and install it. would someone be able to help. sorry

**Comment by vhardono** [comment]
Have you installed homebridge / HOOBS in your Raspberry PI?
Once installed, then you can just use terminal to follow the steps installing Soma plugin

**Comment by mkellsy** [comment]
Stale
