### ISSUE TITLE
Version 2.2.0

### ISSUE THREAD

**Issue by bubez81** [hoobs-org/soma-connect#7]
here is the package of the new version 2.2.0

[https://www.dropbox.com/s/kp2wzf5oa3r949t/soma-connect_2.2.0_armhf.deb?dl=0](url)

**Comment by vhardono** [comment]
Did u managed to get it working?
My last working version is 2.0.8
After i installed 2.2.0, i got “no response” status in Homekit and unable to find Soma devices anymore after i remove them from Homekit
I’m able to see soma plugin is running from SmartShades app and terminal though

**Comment by bubez81** [comment]
i have to check, because at the moment I can't use the shades,I will keep you informed

**Comment by bubez81** [comment]
yes same here....can't find the soma bridge in HomeKit anymore

**Comment by dbogatov** [comment]
What's the link to 2.0.8 deb file?

**Comment by james1301** [comment]
@bubez81 do you have a link to the 2.0.8 file?

**Comment by vhardono** [comment]
@james1301 
Here’s the link for 2.0.8 file
https://www.dropbox.com/s/6p90pzy1sv0bifw/soma-connect_2.0.8_armhf.deb?dl=0

**Comment by costispavlou** [comment]
can someone let me know whether this version works / solves the issues with the connect? i was only able to add one of the accessories.

**Comment by mkellsy** [comment]
We have version 2.2.0 published to our repo.

1. Setup the HOOBS repo
```
wget -qO- https://support.hoobs.org/setup | sudo -E bash -
```

2. Install soma-connect
```
sudo apt install -y soma-connect
```
